
export const activities = [
  { activity: 'Archery', met: 4.3 },
  { activity: 'Badminton', met: 7.0 },
  { activity: 'Basketball, game', met: 8.0 },
  { activity: 'Billiards', met: 2.5 },
  { activity: 'Boating, power', met: 3.5 },
  { activity: 'Bowling', met: 3.0 },
  { activity: 'Boxing, in ring', met: 12.8 },
  { activity: 'Calisthenics (e.g., pushups, situps), vigorous', met: 8.0 },
  { activity: 'Calisthenics, light', met: 3.8 },
  { activity: 'Canoeing, rowing, >6 mph, vigorous', met: 12.5 },
  { activity: 'Canoeing, rowing, light', met: 3.0 },
  { activity: 'Climbing, rock or mountain', met: 8.0 },
  { activity: 'Cricket', met: 5.0 },
  { activity: 'Croquet', met: 3.5 },
  { activity: 'Cycling, <10 mph, leisure', met: 4.0 },
  { activity: 'Cycling, 12-13.9 mph, moderate', met: 8.0 },
  { activity: 'Cycling, 16-19 mph, vigorous', met: 12.0 },
  { activity: 'Cycling, stationary, moderate', met: 7.0 },
  { activity: 'Dancing, aerobic, high impact', met: 7.3 },
  { activity: 'Dancing, ballroom, slow', met: 3.0 },
  { activity: 'Darts', met: 2.5 },
  { activity: 'Diving, springboard or platform', met: 3.5 },
  { activity: 'Fencing', met: 6.0 },
  { activity: 'Fishing, from boat, sitting', met: 2.5 },
  { activity: 'Football, competitive', met: 9.0 },
  { activity: 'Football, touch, flag', met: 8.0 },
  { activity: 'Frisbee, ultimate', met: 8.0 },
  { activity: 'Golf, general', met: 4.8 },
  { activity: 'Gymnastics', met: 4.0 },
  { activity: 'Hacky sack', met: 4.0 },
  { activity: 'Handball, general', met: 12.0 },
  { activity: 'Hiking, cross country', met: 6.0 },
  { activity: 'Hockey, field', met: 8.0 },
  { activity: 'Hockey, ice', met: 8.0 },
  { activity: 'Horseback riding, general', met: 4.0 },
  { activity: 'Horseshoe pitching', met: 3.0 },
  { activity: 'Ice skating, general', met: 7.0 },
  { activity: 'Judo, karate, kick boxing, tae kwan do', met: 10.3 },
  { activity: 'Juggling', met: 4.0 },
  { activity: 'Kayaking', met: 5.0 },
  { activity: 'Lacrosse', met: 8.0 },
  { activity: 'Martial arts, different types, moderate', met: 10.3 },
  { activity: 'Motor-cross', met: 5.0 },
  { activity: 'Polo', met: 8.0 },
  { activity: 'Racquetball, competitive', met: 10.0 },
  { activity: 'Racquetball, casual', met: 7.0 },
  { activity: 'Rock climbing, ascending rock', met: 8.0 },
  { activity: 'Rollerblading', met: 12.3 },
  { activity: 'Rope jumping, fast', met: 12.3 },
  { activity: 'Rope jumping, moderate', met: 10.0 },
  { activity: 'Rowing, stationary, vigorous', met: 8.5 },
  { activity: 'Rowing, stationary, moderate', met: 7.0 },
  { activity: 'Rugby', met: 10.0 },
  { activity: 'Running, 5 mph (12 min/mile)', met: 8.3 },
  { activity: 'Running, 6 mph (10 min/mile)', met: 9.8 },
  { activity: 'Running, 7 mph (8.5 min/mile)', met: 11.0 },
  { activity: 'Running, 8 mph (7.5 min/mile)', met: 11.8 },
  { activity: 'Running, 10 mph (6 min/mile)', met: 14.5 },
  { activity: 'Sailing, boat/board', met: 3.0 },
  { activity: 'Scuba diving', met: 7.0 },
  { activity: 'Shuffleboard', met: 3.0 },
  { activity: 'Skateboarding', met: 5.0 },
  { activity: 'Skiing, cross-country, vigorous', met: 9.0 },
  { activity: 'Skiing, downhill, vigorous', met: 8.0 },
  { activity: 'Skiing, water', met: 6.0 },
  { activity: 'Snorkeling', met: 5.0 },
  { activity: 'Soccer, competitive', met: 10.0 },
  { activity: 'Soccer, casual', met: 7.0 },
  { activity: 'Softball or baseball', met: 5.0 },
  { activity: 'Squash', met: 12.0 },
  { activity: 'Stair-treadmill-ergometer', met: 9.0 },
  { activity: 'Stretching, Hatha Yoga', met: 2.5 },
  { activity: 'Surfing', met: 3.0 },
  { activity: 'Swimming, backstroke', met: 7.0 },
  { activity: 'Swimming, breaststroke', met: 10.0 },
  { activity: 'Swimming, butterfly', met: 11.0 },
  { activity: 'Swimming, freestyle, vigorous', met: 10.0 },
  { activity: 'Swimming, leisurely', met: 6.0 },
  { activity: 'Table tennis (ping pong)', met: 4.0 },
  { activity: 'Tai chi', met: 4.0 },
  { activity: 'Tennis, general', met: 7.3 },
  { activity: 'Track and field (e.g., shot, discus)', met: 4.0 },
  { activity: 'Volleyball', met: 4.0 },
  { activity: 'Volleyball, beach', met: 8.0 },
  { activity: 'Walking, 3.5 mph, brisk pace', met: 3.8 },
  { activity: 'Walking, 4.5 mph, very brisk', met: 5.0 },
  { activity: 'Walking, for pleasure', met: 3.5 },
  { activity: 'Water aerobics', met: 4.0 },
  { activity: 'Water polo', met: 10.0 },
  { activity: 'Weight lifting, vigorous', met: 6.0 },
  { activity: 'Weight lifting, light or moderate', met: 3.0 },
  { activity: 'Wrestling', met: 6.0 },
  { activity: 'Yoga', met: 2.5 },
];
