
export const calculatorGroups = [
  {
    title: 'Core Body Composition',
    calculators: [
      { name: 'BMI Calculator', href: '/bmi' },
      { name: 'Body Fat Percentage Calculator', href: '/body-fat' },
      { name: 'Ideal Body Weight (IBW)', href: '/ideal-weight' },
      { name: 'Lean Body Mass Calculator', href: '/lean-body-mass' },
      { name: 'Fat-Free Mass Index (FFMI)', href: '/ffmi' },
      { name: 'Body Surface Area (BSA)', href: '/bsa' },
      { name: 'Waist-to-Height Ratio', href: '/waist-to-height-ratio' },
      { name: 'Waist-to-Hip Ratio', href: '/waist-to-hip-ratio' },
      { name: 'Body Shape Type Calculator', href: '/body-shape' },
      { name: 'Body Density Calculator', href: '/body-density' },
    ],
  },
  {
    title: 'Weight Management & Goal Setting',
    calculators: [
      { name: 'BMR Calculator', href: '/bmr' },
      { name: 'RMR Calculator', href: '/rmr' },
      { name: 'TDEE Calculator', href: '/tdee' },
      { name: 'Calorie Adjustment for Weight Loss', href: '/calorie-deficit' },
      { name: 'Calorie Adjustment for Weight Gain', href: '/calorie-surplus' },
      { name: 'Calorie Maintenance Calculator', href: '/calorie-maintenance' },
      { name: 'Weight Loss Goal Calculator', href: '/weight-loss-goal' },
      { name: 'Weight Gain Goal Calculator', href: '/weight-gain-goal' },
      { name: 'Weekly Weight Change Tracker', href: '/weight-change-tracker' },
      { name: 'Fat Loss Progress Tracker', href: '/fat-loss-tracker' },
      { name: 'Goal Weight Estimator by Date', href: '/goal-weight-estimator' },
      { name: 'Calorie-to-Weight Conversion', href: '/calorie-to-weight' },
    ],
  },
  {
    title: 'Nutrition & Energy Balance',
    calculators: [
      { name: 'Daily Calorie Needs', href: '/daily-calorie-needs' },
      { name: 'Macronutrient Ratio Calculator', href: '/macronutrient-ratio' },
      { name: 'Protein Intake Calculator', href: '/protein-intake' },
      { name: 'Carb Intake Calculator', href: '/carb-intake' },
      { name: 'Fat Intake Calculator', href: '/fat-intake' },
      { name: 'Water Intake Calculator', href: '/water-intake' },
      { name: 'Calorie Burn by Activity Calculator', href: '/calorie-burn-by-activity' },
      { name: 'Workout Calorie Tracker', href: '/workout-calorie-tracker' },
      { name: 'Meal Calorie Split Calculator', href: '/meal-calorie-split' },
      { name: 'Hydration Tracker', href: '/hydration-tracker' },
    ],
  },
  {
    title: 'Fitness & Performance',
    calculators: [
      { name: 'One Rep Max (1RM) Calculator', href: '/one-rep-max' },
      { name: 'Strength-to-Weight Ratio', href: '/strength-to-weight-ratio' },
      { name: 'VO2 Max Estimator', href: '/vo2-max' },
      { name: 'Activity MET Value Calculator', href: '/met-value' },
      { name: 'Steps to Calories Calculator', href: '/steps-to-calories' },
      { name: 'Walking/Running Calorie Calculator', href: '/walking-running-calories' },
      { name: 'Daily Activity Level Estimator', href: '/activity-level-estimator' },
      { name: 'Weekly Workout Load Calculator', href: '/weekly-workout-load' },
    ],
  },
  {
    title: 'Health Risk Assessment',
    calculators: [
      { name: 'Obesity Risk Calculator', href: '/obesity-risk' },
      { name: 'Metabolic Age Calculator', href: '/metabolic-age' },
      { name: 'Heart Disease Risk Calculator', href: '/heart-disease-risk' },
      { name: 'Diabetes Risk by BMI', href: '/diabetes-risk' },
      { name: 'Body Fat Health Zone Classifier', href: '/body-fat-zone' },
      { name: 'Body Type Visualizer', href: '/body-type-visualizer' },
      { name: 'BMI Percentile for Age (Teens)', href: '/bmi-percentile-teen' },
    ],
  },
];
